#!/bin/bash

# Stolen from:
# http://redkrieg.com/2011/03/14/adding-notifications-to-finch/

latest_line=`find ~/.purple/logs/jabber -mtime -1 -printf "%T@ %Tx %TX %p\n" | sort -n -r | head | cut -d ' ' -f 2- | awk '{print $NF}' | head -1 | xargs tail -1 | sed -e 's#<[^>]*>##g'`
echo $latest_line
twmnc -t "`echo $latest_line | cut -d ':' -f 3 | awk -F ')' '{print $2}'`" -c "`echo $latest_line | cut -d ':' -f 4-`"
